// Generated by gen-tool
// DO NOT EDIT!
package config;
import java.awt.*;
import java.util.*;

public class BasicItem_CommonInfo
{

	public Integer Id;

	public String Icon;

	public Integer Quality;

	public Integer Price;

	public ArrayList<Integer> LimitNum;

	public Integer Acauire;

	public String ConsumeItem;

	public Integer ConsumeCoin;

	public Integer FormatIndex;

	public BasicItem_CommonQuality Quality1;

	public Date ShowTime;

	public Date EndTime;

	public Color TextColor;

}
