// Generated by gen-tool
// DO NOT EDIT!
package config

type BasicItem_Common struct {
	Content []*BasicItem_CommonInfo
}
type BasicItem_CommonInfo struct {
	Id int32

	Icon string

	Quality int32

	Price int32

	LimitNum int32

	Acauire int32

	ConsumeItem string

	ConsumeCoin int32

	FormatIndex int32
}
